@startuml model

object GenreEL <<enumeration>> {
  Breakbeats
  Chill Out
  Commercial Dance
  Drum & Bass
  Dubstep
  Electro House
  Electronica
  Funk / R&B
  Hard Dance
  Hardcore Techno
  Hip Hop
  Indie / Underground
  Minimal
  Progressive House
  Psychedelic Trance
  Reggae
  Tech House
  Techno
  Traditional House
  Trance
  Trap
}

object Event {
  ID
  name
  genres
  date
  time
}

object DJ {
  ID
  name
  genre
}

object User {
  username
  password
}

note left
  <<invariant>>
  Further participants can be added to de event iff 
  capacity of the venue is greater / equal than the number of participants
end note

object Admin {

}

object Participant {
  
}

object Venue {
  ID
  name
  address
  capacity
  contact
}

object Feedback {
  ID
  stars
  comment
}

note left
  <<invariant>>
  Applies only in case of event feedback:
  Creation of feedback allowed iff event already happened
  (date and time in the past)
end note

Admin -down-|> User
Participant -right[hidden]- Admin
Participant -down-|> User
Event "*" -up-> "*" User : participants
DJ -right[hidden]-> GenreEL

Event "1" --> "*" Feedback : feedbacks
Venue "1" --> "*" Feedback : feedbacks
DJ "1" --> "*" Feedback : feedbacks

Event "*" -left-> "1" Venue : venue
Event "*" -right-> "1..*" DJ : djs

@enduml
