@startuml model

object GenreEL <<enumeration>> {
  Breakbeats
  Chill Out
  Commercial Dance
  Drum & Bass
  Dubstep
  Electro House
  Electronica
  Funk / R&B
  Hard Dance
  Hardcore Techno
  Hip Hop
  Indie / Underground
  Minimal
  Progressive House
  Psychedelic Trance
  Reggae
  Tech House
  Techno
  Traditional House
  Trance
  Trap
}

object Event {
  ID
  name
  genres
  date
  time
}

object Location {
  ID
  name
  address
  contact
}

object DJ {
  ID
  name
  genre
}

object Feedback {
  ID
  content
}

note left
  <<invariant>>
  Applies only in case of event feedback:
  Creation of feedback allowed iff event already happened
  (date and time in the past)
end note


Event "1" --> "*" Feedback : feedbacks
Location "1" --> "*" Feedback : feedbacks
DJ "1" --> "*" Feedback : feedbacks

@enduml