const GenreEL = Object.freeze({
  BASS_MUSIC: "Bass Music",
  BREAKBEATS: "Breakbeats",
  BIG_BEAT: "Big Beat",
  BIG_ROOM_HOUSE: "Big Room House",
  CHILL_OUT: "Chill Out",
  COMMERCIAL_DANCE: "Commercial Dance",
  DEEP_HOUSE: "Deep-House",
  DISCO: "Disco",
  DRUM_AND_BASS: "Drum & Bass",
  DUBSTEP: "Dubstep",
  ECHO_POP: "Echo Pop",
  ELECTRO_HOUSE: "Electro House",
  ELECTRONICA: "Electronica",
  ELECTRO: "Electro",
  FUNK_R_AND_B: "Funk / R&B",
  FUTURE_BASS: "Future Bass",
  HARD_DANCE: "Hard Dance",
  HARD_TRANCE: "Hard Trance",
  HARDCORE_TECHNO: "Hardcore Techno",
  HIP_HOP: "Hip Hop",
  HOUSE: "House",
  INDIE_UNDERGROUND: "Indie / Underground",
  MINIMAL_TECHNO: "Minimal Techno",
  PROGRESSIVE_HOUSE: "Progressive House",
  PSYCHEDELIC_TRANCE: "Psychedelic Trance",
  REGGAE: "Reggae",
  TECH_HOUSE: "Tech House",
  TECHNO: "Techno",
  TRADITIONAL_HOUSE: "Traditional House",
  TROPICAL_HOUSE: "Tropical House",
  TRANCE: "Trance",
  TRAP: "Trap",
});

export default GenreEL;