const GenreEL = Object.freeze({
  BREAKBEATS: "Breakbeats",
  CHILL_OUT: "Chill Out",
  COMMERCIAL_DANCE: "Commercial Dance",
  DRUM_AND_BASS: "Drum & Bass",
  DUBSTEP: "Dubstep",
  ELECTRO_HOUSE: "Electro House",
  ELECTRONICA: "Electronica",
  FUNK_R_AND_B: "Funk / R&B",
  HARD_DANCE: "Hard Dance",
  HARDCORE_TECHNO: "Hardcore Techno",
  HIP_HOP: "Hip Hop",
  INDIE_UNDERGROUND: "Indie / Underground",
  MINIMAL: "Minimal",
  PROGRESSIVE_HOUSE: "Progressive House",
  PSYCHEDELIC_TRANCE: "Psychedelic Trance",
  REGGAE: "Reggae",
  TECH_HOUSE: "Tech House",
  TECHNO: "Techno",
  TRADITIONAL_HOUSE: "Traditional House",
  TRANCE: "Trance",
  TRAP: "Trap",
});

export default GenreEL;